import os


SIMULATOR_BASE_URL = os.getenv("SIMULATOR_BASE_URL", "http://simulator:8080")
DEVICES_ENDPOINT = f"{SIMULATOR_BASE_URL}/api/devices/"

PROCESSING_REPLICAS = [
    os.getenv("PROCESSING_REPLICA_1", "http://processing-1:8100"),
    os.getenv("PROCESSING_REPLICA_2", "http://processing-2:8100"),
    os.getenv("PROCESSING_REPLICA_3", "http://processing-3:8100"),
]

BROKER_REQUEST_TIMEOUT_SECONDS = float(
    os.getenv("BROKER_REQUEST_TIMEOUT_SECONDS", "1.0")
)

BROKER_PARTIAL_FAILURE_LOG_INTERVAL_SECONDS = int(
    os.getenv("BROKER_PARTIAL_FAILURE_LOG_INTERVAL_SECONDS", "15")
)

BROKER_QUEUE_MAXSIZE = int(
    os.getenv("BROKER_QUEUE_MAXSIZE", "20000")
)

BROKER_WORKER_COUNT = int(
    os.getenv("BROKER_WORKER_COUNT", "16")
)

BROKER_REPLICA_RETRY_AFTER_SECONDS = int(
    os.getenv("BROKER_REPLICA_RETRY_AFTER_SECONDS", "10")
)